### ISSUE TITLE
Add children property for Events

### ISSUE THREAD

**Issue by breyten** [popolo-project/popolo-spec#103]
An event can have a parent id, which is useful for specifying relationships between events. it would also be useful to add the inverse of that property (children), to preserve the ordering of parent and child events.

The main use case that I'm looking at right now is that I'm trying to describe a meeting in Popolo with Meeting items, where the order of meeting items is definitely important.

Any thoughts on this? (Is there another ay to do this?)

**Comment by jpmckinney** [comment]
Sorry, that was an oversight. Area and Organization already had a `children` property, but I forgot to add one to `Event`.

**Comment by breyten** [comment]
Heh, I didn't know ;) Thanks! :+1:
