### ISSUE TITLE
Standards for classification type in organization

### ISSUE THREAD

**Issue by kaerumy** [popolo-project/popolo-spec#105]
It would be good to have some reference vocabulary for this, so that we can extract organizations by type:

eg.
- statutory body (organization created by statute)
- public limited company
- private limited company
- parliamentary committee
- company board (Board of directors)
- management (CxOs)
- ministerial cabinet

Example queries:

Person has been a part of A, B & C parliamentary/senate oversight committees.
Person is currently a director in A, B, C companies (board of directors)

For reuse, I'm hoping that parliamentary/senate oversight committee might use some internationally common naming convention.

**Comment by jpmckinney** [comment]
Duplicate #91 Agreed it's important!
