### ISSUE TITLE
"reports to" for committees and other types of organizations

### ISSUE THREAD

**Issue by kaerumy** [popolo-project/popolo-spec#106]
How do we implement this in popolo, or is a field needed?

Various committees, commissions etc. are set up to report on something, to an organization or person.

Examples:
- Parliamentary Accountability Committee on Government Expenditure created under Parliament and reports findings to parliament.
- Malaysia Petroleum Resources Corporation is an agency reporting to the Prime Minister's Office
- Tenders Committee of Telekom Berhad reports to Board of Directors of Telekom Berhad.

**Comment by jpmckinney** [comment]
In many cases, simply using organizational hierarchies achieves this. Parliamentary committees are suborganizations of parliament, and they therefore report to parliament. Are there any cases where organizational hierarchy would be inappropriate?

**Comment by kaerumy** [comment]
On further thought, I think sub-organization is best. A government organization or committee has to exist as a creation of something else. When this information is missing, parent is probably best left empty, until the parent organization can be found in our case.
