### ISSUE TITLE
Can a post have all value as null?

### ISSUE THREAD

**Issue by sweemeng** [popolo-project/popolo-spec#116]
I have read the spec, I noticed that if all the field in a post object don't have value, it is still considered as a valid Post

http://www.popoloproject.com/schemas/post.json

Am my interpretation correct? Personally I think at least the role of a post should not be null.

**Comment by jpmckinney** [comment]
`role` is optional - it's fine to just have a `label`. It's unusual, but JSON Schema doesn't allow for complex validation like "invalid if all fields are empty" to my knowledge.

**Comment by sweemeng** [comment]
Alright, thanks for clarification.
