### ISSUE TITLE
Define models for elections?

### ISSUE THREAD

**Issue by pmackay** [popolo-project/popolo-spec#117]
@tfgg is doing some great work on election codes (see http://tfgg.me/2015/11/10/election-codes.html) and core fields. Has the idea of defining a model for elections and candidates been considered as something Popolo could cover?

**Comment by jpmckinney** [comment]
An election would be treated as an [Event](http://www.popoloproject.com/specs/event.html) in Popolo. There's a long, developed discussion about candidates in this issue: https://github.com/popolo-project/popolo-spec/issues/104

I'll close in favor of the open issue. But in short, yes, both can be modeled in Popolo, but the documentation needs to be improved to make that more obvious and guided.
