### ISSUE TITLE
Range of `onBehalfOf`

### ISSUE THREAD

**Issue by akuckartz** [popolo-project/popolo-spec#118]
OpenGovLD currently has a range of `onBehalfOf` consisting of both `Organization` and `Person`. Popolo seems to restrict the range to `Organization`: "The organization on whose behalf the person is a member of the organization" (http://www.popoloproject.com/specs/membership.html)

I would like to see a common solution.

The main reason for making it possible to be a member on behalf of a person in OpenGovLD was to enable statements that a person is a member on behalf of him- or herself and not behalf of a party or other organization (subject and object would simply be identical in such cases).

Any suggestions?

**Comment by jpmckinney** [comment]
To say you are on your own behalf is the same as saying you are on no one's behalf, so I would simply leave the value blank to state that a person is on their own behalf.

**Comment by akuckartz** [comment]
> To say you are on your own behalf is the same as saying you are on no one's behalf

I do not think that _reflexivity_ can be presupposed for the property `onBehalfOf` !

For another potential use of `onBehalfOf` with range `Person` see #119

**Comment by jpmckinney** [comment]
No one is claiming the property is reflexive.

**Comment by jpmckinney** [comment]
Re: the use case to #119, it applies to attendance-on-behalf-of, not membership-on-behalf-of. So, closing this issue, and leaving the other open.
