### ISSUE TITLE
Ensure equity and inclusion with gender pronoun property for Person class

### ISSUE THREAD

**Issue by geekpete** [popolo-project/popolo-spec#129]
While the gender property is derived from the foaf specification which seems inclusive in its explanation of how gender should be dealt with:
http://xmlns.com/foaf/spec/#term_gender

deriving pronouns from a gender property is becoming increasingly insufficient for inclusion and equity, especially for democratic standards that are aiming for these values:

https://www.popoloproject.com/specs/person.html:
```
gender

    To determine personal pronouns, e.g. “John Doe will be at his constituency office next week.”
```

An additional property to specify personal pronouns is probably a step in the right direction.

For more information on what this means and why it's important, see the FOAF specification mentioned earlier or maybe these:

https://www.hrc.org/resources/talking-about-pronouns-in-the-workplace

and

https://assets2.hrc.org/files/assets/resources/TalkingAboutPronouns_onesheet_FINAL.pdf

**Comment by jpmckinney** [comment]
@geekpete Do you have a proposed term to use for this property?

**Comment by geekpete** [comment]
`pronouns` is probably easiest.

**Comment by jpmckinney** [comment]
@geekpete Sounds good to me. Can you prepare a PR for this new property? At minimum, you would need to edit `specs/person.md` and `schemas/person.json`.
