### ISSUE TITLE
Document class and properties

### ISSUE THREAD

**Issue by jpmckinney** [popolo-project/popolo-spec#13]
Add a Document class to represent things like bills, agendas, etc. The base Document class may be fairly generic, with subclasses providing additional properties.
## Issues
- The requirements for drafting legislation are sometimes in tension with those of parsing and displaying legislation. Different specifications/standards may emerge that are better tailored for one or the other.
## Existing specifications
- [Dublin Core](http://dublincore.org/documents/dcmi-terms/)
- [FOAF Document](http://xmlns.com/foaf/spec/#term_Document): topic (dcterms:subject), primaryTopic, sha1
- [Project Documents Ontology](http://vocab.deri.ie/pdo): adds no document properties not covered by Dublin Core
### Legislative
- [Akoma Ntoso](http://www.akomantoso.org/)
- [metasausage](http://blog.law.cornell.edu/metasausage/downloads-and-related-information/) includes sponsorships
- [OASIS LegalXML](http://www.legalxml.org/): [LegalDocML technical committee](https://www.oasis-open.org/committees/tc_home.php?wg_abbrev=legaldocml) and [mailing list](https://lists.oasis-open.org/archives/legaldocml/)
  - [Discussion on the extension of Akoma Ntoso for the US code pilot case](https://www.oasis-open.org/committees/document.php?document_id=47993&wg_abbrev=legaldocml)
- NIEM: Document*
- [Crown Legislation Markup Language (CLML)](http://webarchive.nationalarchives.gov.uk/20100225080346/opsi.gov.uk/legislation/schema/)
- [xml.house.gov](http://xml.house.gov/)
- [Finlex Legislation Metadata Schema](http://schema.onki.fi/finlex-laki/)
- [OParl.de](https://github.com/OParl/specs) Paper, File, etc.
- [OpenCivicData](http://docs.opencivicdata.org/en/latest/proposals/0006.html) Bill
- [BillIt](https://github.com/ciudadanointeligente/bill-it/tree/master/app/models) component
- [Councilmatic](https://github.com/open-city/councilmatic)

**Comment by jpmckinney** [comment]
For the basic use cases, Dublin Core is sufficient.

For bills: While many organizations write software dealing with bills, it's unclear if any software yet exists that crosses borders. Until there's evidence of reuse across jurisdictions, there is not a strong use case for creating an international data interchange format.

This issue can be reopened if interest is expressed in reviving the discussion.

**Comment by akuckartz** [comment]
I am in contact with people working for the European Parliament regarding the Akoma Ntoso FOSS implementation AT4AM for All. And I am interested in combining that with OpenGovLD, Popolo etc.

(I think that it would be good to put information as that compiled by @jpmckinney on a Wiki instead of hiding it in closed issues!)

**Comment by jpmckinney** [comment]
Feel free to copy it to a wiki!

**Comment by jpmckinney** [comment]
I remembered we have this page https://github.com/opennorth/popolo-spec/wiki/Miscellaneous-specifications I'll copy things there.
