### ISSUE TITLE
Specification for protocols / minutes / proceedings?

### ISSUE THREAD

**Issue by torfsen** [popolo-project/popolo-spec#130]
Perhaps I've missed it, but it seems that currently Popolo doesn't have any specific entities for describing the minutes / proceedings of a meeting:

- Where and when a meeting took place
- Who participated
- A transcription of who said what

I'm also not aware of any other ontologies that cover this subject (again I might be missing something), and I think it would fit nicely within the scope of the project.

**Comment by jpmckinney** [comment]
For transcripts, I recommend Akoma Ntoso. A good subset is described by mySociety's project, SayIt: https://sayit.mysociety.org/about/developers

Otherwise, Popolo does have an Event class which is sufficient to describe where, when, who, etc.
