### ISSUE TITLE
Poplus.org link no longer resolves to correct destination

### ISSUE THREAD

**Issue by devinbalkind** [popolo-project/popolo-spec#131]
When I open the link (http://poplus.org/components/current/) I'm directed to Swedish advertisements for gambling etc.

Clicked from attached image.
![screencapture-popoloproject-2021-01-03-23_04_52-edit](https://user-images.githubusercontent.com/444311/103500142-7c81e000-4e18-11eb-9060-15f3ae86f048.png)

**Comment by jpmckinney** [comment]
Thanks, I've removed the link.

The link wasn't hacked - the Poplus project ended and its sponsors let the domain lapse.
