### ISSUE TITLE
Specify how to denormalize MongoDB?

### ISSUE THREAD

**Issue by jpmckinney** [popolo-project/popolo-spec#14]
MongoDB implementations will inevitably want to denormalize the data. How can we ensure denormalizations conform to some standard?

**Comment by konklone** [comment]
Could the spec provide an option for a `memberships` sub-field on people, where the fields underneath that are the same as in the standalone Memberships collection - sans the "member" field?

**Comment by jpmckinney** [comment]
Yup, that's how we would do it. There's a separate JSON issue in case there's a reason for the MongoDB and JSON serializations to differ: https://github.com/opennorth/popolo-standard/issues/23

**Comment by konklone** [comment]
Ah, okay. It was closed, is why I posted here.

**Comment by jpmckinney** [comment]
Yeah, I accidentally closed it when trying to label it :)

**Comment by jpmckinney** [comment]
Continuing in #23
