### ISSUE TITLE
Example in Relations needing both Membership and Posts

### ISSUE THREAD

**Issue by dracos** [popolo-project/popolo-spec#15]
“Some use cases may therefore require both Post and Membership classes to satisfy their requirements.”

I think it would be useful to have an example, say of the mentioned Member of Parliament for Avalon, that requires both Memberships and Posts to both handle historical information and have the position represented when no-one holds it, which I think might be a common situation. Let's take two people, Joe Bloggs and Fred Smith; Joe is the current MP for Avalon, Fred is a previous one; Joe is going to resign in a paragraph or two. If I've understood it right (quite possibly not :) ), am I right in that Joe needs both a Membership and a Post to be able to both assign the right label and have a start date?

Before resignation:
- Post: label: Member of Parliament for Avalon, role: Member of Parliament, org: Parliament, person: Joe Bloggs.
- Membership: role: Member of Parliament, person: Fred Smith, org: Parliament, start_date: 2005-02-01. end_date: 2010-04-05.
- Membership: role: Member of Parliament, person: Joe Bloggs, org: Parliament, start_date: 2010-05-06, end_date: -empty- (or 'future' or whatever is needed if you want to know difference between unknown and future).

Joe resigns:
- Post: label: Member of Parliament for Avalon, role: Member of Parliament, org: Parliament, person: -empty-.
- Membership: role: Member of Parliament, person: Fred Smith, org: Parliament, start_date: 2005-02-01. end_date: 2010-04-05.
- Membership: role: Member of Parliament, person: Joe Bloggs, org: Parliament, start_date: 2010-05-06, end_date: 2012-02-27.

As one question, how do I know who were all the previous Members of Parliament for Avalon?

**Comment by jpmckinney** [comment]
Yes, to have a start date Joe would need a Membership. This example is correct.

To know all the previous members of parliament, query:

```
db.memberships.distinct('person_id', {
  end_date: {$ne: null, $lt: new Date()},
  role: "Member of Parliament",
  organization_id: "foo",
});
```

**Update:** (actually, you need to convert `new Date()` to a ISO 8601:2004 string, but for brevity...)

(With respect to the certainty of information, Popolo currently assumes certainty for everything except dates - and even then, you must have at least some part of the date's information. For the difference between unknown and absent, I've opened https://github.com/opennorth/popolo-standard/issues/17)

**Comment by jpmckinney** [comment]
If I add an example, do you think it should be in the same html page, or can I link to it and put it on another page? That section of the spec is already long (and will likely get longer as this is the part with the most confusion and disagreement).

**Comment by dracos** [comment]
Unless I've missed something, that query doesn't tell me which of those members were the previous MPs for Avalon, just all previous MPs (and I can't see how I would then know which of those were MPs for Avalon).

(A separate page for examples would be good.)

**Comment by jpmckinney** [comment]
Yes, I just noticed your question was "all the previous Members of Parliament for Avalon" :) Sorry about that.

We don't have the concept of an "Area" yet, which would help disambiguate MPs, since each MP represents a different area. I guess both Posts and Memberships would have an `area_id` property then to satisfy this use case.

I'm now wondering if there's another example where `area_id` would not suffice for disambiguation.

Once we have areas in Popolo (I left them out because there's about a dozen existing standards to review), we could do:

```
db.memberships.distinct('person_id', {
  end_date: {$ne: null, $lt: new Date()},
  role: "Member of Parliament",
  organization_id: "foo",
  area_id: "bar",
});
```

**Comment by jpmckinney** [comment]
Given that, if we care about start dates, we will always need a Membership object, this may be an argument in favor of redesigning Posts to be less like Memberships, while still fulfilling the use cases that required them in the first place. The OpenStates team had a suggestion, and I've invited them to continue the discussion here.

**Comment by jpmckinney** [comment]
This is resolved in this proposal: https://github.com/opennorth/popolo-standard/wiki/2013-02-28-Rework-Membership-and-Post

**Comment by jpmckinney** [comment]
Done locally. Push coming soon!
