### ISSUE TITLE
Store last modified date

### ISSUE THREAD

**Issue by evdb** [popolo-project/popolo-spec#19]
It would be very useful to have a last modified date. In PopIt we would use this to list all the documents that had changed after the last check.

It could be optional, but if included should:
- be under the key `last_modified` at the top_level
- be a full timestamp in UTC
- reflect any change to the document or nested documents - not just meaningful changes

**Comment by jpmckinney** [comment]
How's `dcterms:modified` for RDF and `updated_at` for JSON/MongoDB (since many ODMs magically update that property)? Why do you prefer `last_modified`? I know that's the name of the HTTP header.

In terms of your point 3 (it's helpful to use ordered lists :), we can define the property to make this usage clear.

**Comment by evdb** [comment]
`modified` works for me.

I personally don't like using 'updated' in the naming for this, as it implies that the information was corrected or added to at that time, rather than just changed. Having a process for storing historic versions of an entry, or for continually ensuring correctness, is probably outside the scope of popolo.

**Comment by jpmckinney** [comment]
Re: historical versions, see #3 at [the wiki](https://github.com/opennorth/popolo-standard/wiki/Changes-over-time).

In terms of choosing a name, I'd prefer something that ORMs/ODMs already use. Here's a brief survey:

[mongoose-troop](https://github.com/tblobaum/mongoose-troop#timestamp) uses `created` and `modified` by default, as does CakePHP. Agile Toolkit (PHP) uses `created_dts` and `updated_dts`. PHP's DataMapper uses `created` and `updated` by default. In Python, Django and SQLAlchemy seems to have no preference for naming.

All Ruby ORMs I know (ActiveRecord, Mongoid, MongoMapper, DataMapper, Sequel, CouchPotato), use `created_at` and `updated_at`, as do Propel and Doctrine in PHP (used by Symfony and CodeIgniter).

I can't find what Zend Framework uses.

**Comment by evdb** [comment]
I'm not too fussed about the naming, just as long as it is clear that the time stamp refers to any change, not a significant one.

Regarding the historic versions I was not thinking about storing changes that happened to the person/org at various times in their history. Instead I meant previous documents stored in the database to enable things like edit histories and rollbacks. I see this as being something that the app should provide, not something for the Popolo standard. What Wikipedia would call 'revisions'.

**Comment by jpmckinney** [comment]
Ah, yes, I don't currently know a use case that would require standardization around how edit histories are represented.

We'll make the semantics of the `modified` / `updated_at` field clear in the spec.

**Comment by jpmckinney** [comment]
+1 from Robert Cheetham
