### ISSUE TITLE
Area class and properties

### ISSUE THREAD

**Issue by evdb** [popolo-project/popolo-spec#21]
**New issue description:** To close this issue (additional feedback would go in new issues):
- [x] Add JSON-Schema
- [x] Add JSON-LD context
- [x] Link Area from the navigation

---

Some posts (like "MP for Avalon", "UK's Ambassador to the USA" ) require an area. How should areas be represented and stored?

In PopIt we were going to use a string field which could either be the name of the area or a url to an external service that has an entry for an area (like MapIt). More details and a discussion at mysociety/popit#193

In the W3C [org ontology](http://www.w3.org/TR/vocab-org/) they allow organisations to have [sites](http://www.w3.org/TR/vocab-org/#class--site) (an office or a premise) and a [location](http://www.w3.org/TR/vocab-org/#property--location) (an internal physical location, like where mail is delivered). [Posts](http://www.w3.org/TR/vocab-org/#class--post) are a sub class of organisations so can have sites too. However neither of site or location would seem intended for an entire administrative area.

**Comment by jpmckinney** [comment]
I would like Popolo to eventually deoine an Area class and properties. If you want to help with that, you can create an [inventory of terms](http://popoloproject.com/data/terms.html) and a [survey of existing standards](http://popoloproject.com/data/survey.html) for areas, based on the following:

## Area
- [x] Schema.org has [`schema:Place`](http://schema.org/Place) and [`schema:GeoShape`](http://schema.org/GeoShape)
- [x] [Dublin Core](http://dublincore.org/documents/dcmi-terms/) has `dc:Location` and `dc:spatial`
- [x] [NeoGeo](http://geovocab.org/doc/neogeo/)
- [x] [GADM](http://gadm.geovocab.org/ontology.html)
- [x] [Ordnance Survey](http://data.ordnancesurvey.co.uk/oswebsite/ontology/), in particular [Spatial Relations](http://data.ordnancesurvey.co.uk/ontology/spatialrelations/) and [Geometry](http://data.ordnancesurvey.co.uk/ontology/geometry/)
- [x] [LinkedGeoData](http://linkedgeodata.org/) (OSM)
- [x] [FAO](http://www.fao.org/countryprofiles/geoinfo/en/) [RDF](http://www.fao.org/countryprofiles/geoinfo/geopolitical/resource/)
- [x] [GeoNames](http://www.geonames.org/ontology/documentation.html)
- [x] metasausage adds a `legis:hasLegislator` property to `schema:Place`, and has `hasState` and `hasDistrict` properties for `legis:Legislator`.
- [x] [Getty Thesaurus of Geographic Names](http://www.getty.edu/research/tools/vocabularies/tgn/index.html), recommended by Dublin Core [LOD](http://www.getty.edu/research/tools/vocabularies/lod/) [ontology](http://vocab.getty.edu/ontology.html) (TGN not yet available as LOD)
- [x] [W3C Locations and Addresses Community Group](http://www.w3.org/community/locadd/) ([list of existing standards](http://www.w3.org/community/locadd/wiki/SoA_Survey))
- [x] [ISO 19115](http://www.iso.org/iso/catalogue_detail.htm?csnumber=26020) Geographic information metadata
- [x] More [geometry](http://lov.okfn.org/dataset/lov/details/vocabularySpace_Geometry.html) and [geography](http://lov.okfn.org/dataset/lov/details/vocabularySpace_Geography.html) ontologies
- [x] http://reference.data.gov.uk/def/parliament defines `represents` (Seat is a subclass of `org:Post`):

``` xml
<rdf:Property rdf:about="http://reference.data.gov.uk/def/parliament/represents">
  <rdf:type rdf:resource="http://www.w3.org/2002/07/owl#ObjectProperty"/>
  <rdfs:comment xml:lang="en">The constituency that the MP holding this seat in parliament represents.</rdfs:comment>
  <rdfs:domain rdf:resource="http://reference.data.gov.uk/def/parliament/Seat"/>
  <rdfs:isDefinedBy rdf:resource="http://reference.data.gov.uk/def/parliament"/>
  <rdfs:label xml:lang="en">Represents</rdfs:label>
  <skos:editorialNote xml:lang="en">No range set on this though for the House of Commons it will be a &lt;http://data.ordnancesurvey.co.uk/ontology/admingeo/WestminsterConstituency&gt;.</skos:editorialNote>
</rdf:Property>
```

Irrelevant to current spec:
- [SWIG Basic Geo](http://www.w3.org/2003/01/geo/) (points)
- [Global Location Number (GLN)](http://en.wikipedia.org/wiki/Global_Location_Number) (identifier scheme)
- [GEOnet Names Server (GNS)](http://en.wikipedia.org/wiki/GEOnet_Names_Server) (identifier scheme)
- [Geographic Names Information System (GNIS)](http://en.wikipedia.org/wiki/Geographic_Names_Information_System) (identifier scheme)

We can postpone this work for now - we have enough to review with just people and orgs, and areas are distinct enough that our decisions about people/orgs shouldn't influence what happens with areas. Not all the above will be relevant, but it's important for the survey to document why an existing standard is unsuitable. Some, for example, may only provide canonical names for places (which is still important to document).

If you must have at least a property for linking posts/memberships to areas in the short term, then in the best case you would find an appropriate existing property for that link, and in the worst case you would come up with something yourself, which may not make it into Popolo once someone volunteers to review all the above standards. I would estimate maybe a week full-time to prepare something like the current Popolo spec for areas.

Coming up with standards goes against the usual hacker ethic of scrapping something together and seeing what works, so I would totally understand the feeling that this is a lot of "process". However, if you want people to adopt your standard, you either need to have a lot of power (dictator), or a lot of support (consensus). With Popolo, I think we have to content ourselves with consensus.

For what it's worth, Billy stores a path to the boundary stored in [represent-boundaries](https://github.com/rhymeswithcycle/represent-boundaries).

I had started on an Area class before deciding that I should push out people/orgs to start and then work on areas later. I put my [very bare beginnings](https://github.com/opennorth/popolo-standard/wiki/Area) on the wiki.

**Comment by jpmckinney** [comment]
Note: recommend open civic data division IDs.

**Comment by jpmckinney** [comment]
Note from call: ensure a distinction can be made between places and boundaries.

**Comment by jpmckinney** [comment]
Note from wiki: MapIt supports nested areas through a `parent_area` column on the `mapit_area` table. The [boundary service](https://github.com/rhymeswithcycle/represent-boundaries) used by Billy does not support nested areas.

**Comment by jpmckinney** [comment]
Adding link to https://github.com/mysociety/popit/issues/193#issuecomment-12362672

**Comment by jpmckinney** [comment]
See `area` property at https://github.com/mysociety/popit-api/blob/master/schemas/popolo%2Bmysociety/post.json

**Comment by paultag** [comment]
I did some rough work on this, here's a brain dump:

I tried a few conversions with the key name `division_id`. This seemed to work great. I stored the [OCD Division ID](https://github.com/opencivicdata/ocd-division-ids) for the geo-spatial area that it relates to.

It was also added to organizations, which was handy as well, under the same name, `division_id`.

The use case is two-fold:

I want to find all organizations that are stored for the city of Boston, MA (`ocd-division/country:us/state:ma/place:boston`), which includes such things as the Boston City Council, or other state-wide organizational entities.

In addition, since districts can be expressed as division IDs (`ocd-division/country:us/state:ma/sldl:barnstable_dukes_and_nantucket`), it's quite useful to see who holds office for that entity, adding a relation on membership called `division_id` would allow for this, which allows for finding people by a shape (such as district, city or ward)

Happy to elaborate on any of this!

**Comment by jpmckinney** [comment]
Thanks, @paultag ! What do you mean by conversions?

**Comment by paultag** [comment]
Ah, sorry, @jpmckinney - I was talking about the OpenStates => Popolo / OCD conversions -- I was playing with legislative district stuff (apropos our recent thread) for OCD-ized OpenStates data -- but this does apply to non-converted data too! :)

**Comment by akuckartz** [comment]
Also potentially relevant:
- GeoJSON
- GeoSPARQL

**Comment by paultag** [comment]
@jpmckinney  Any chance we could add `division_id` (defined as an OCD division ID) to the spec? It'd be really great for the tooling we're building up - I was thinking of using it optionally both on orgs and posts (memberships seem awkward to me, but they might be cool for some situations as well)

**Comment by jpmckinney** [comment]
I'll add it to the spec when I have a moment, but feel free to use `division_id` in Pupa in the meantime. mySociety has been using `area`, but I think that should be reserved for the actual geographical boundary.

**Comment by jpmckinney** [comment]
@paultag Just thinking about possible implementation concerns. `area` is a term that can refer to a geographic region without a defined boundary (e.g. "the upscale area of town"), whereas division is more likely an area with a defined boundary. So, `area` is a superset of `division`. To reduce the number of terms, we might consider using `area_id`, which if it begins with `ocd-division`, is understood to be an OCD division. Any opinion on that?

**Comment by akuckartz** [comment]
I am having a look at some projects which attempt to adapt the European INSPIRE specifications to Linked Data. Some of them hopefully are also relevant outside Europe.

**Comment by paultag** [comment]
@jpmckinney - sorry, missed this -- I don't really mind what the name is (I've just been using `division_id` in my code so far), but it seems like any "area" could be issued a division ID (e.g. I can't think of areas that wouldn't be able to be issued a division ID (perhaps if you're talking about the earth on the whole, that might cause issues :)  )

**Comment by jpmckinney** [comment]
@akuckartz Do you have any links? I know about this group: http://www.w3.org/community/locadd/ and this spec: http://www.w3.org/ns/locn

**Comment by akuckartz** [comment]
@jpmckinney So far I have compiled a small number of links on this page:
https://github.com/OParl/specs/wiki/Geo-und-INSPIRE

Quite a few interesting papers were submitted for the W3C Workshop "Linking Geospatial Data" (link is on the Wiki page).

**Comment by jpmckinney** [comment]
@paultag I've added `area_id` and `area` properties to Membership, Organization, and Post, and added a first draft of an Area spec: http://popoloproject.com/specs/area.html

**Comment by jpmckinney** [comment]
Closing issue. Report feedback in new issues.
