### ISSUE TITLE
Event class and properties

### ISSUE THREAD

**Issue by jpmckinney** [popolo-project/popolo-spec#22]
#18 and #20 point to the need for an Event class, which was identified during the initial spec's development as an eventual requirement beyond the basic people/org classes. Events are particularly relevant to changes to organizations, memberships, people, e.g. mergers, appointments, marriages, etc.

Once Event is added, we might consider adding `start_event` and `end_event` properties to Membership, to satisfy the [TheyWorkForYou use case](https://github.com/mysociety/theyworkforyou/blob/master/www/includes/easyparliament/member.php#L36) described in #20.

Motion and VoteEvent refer to a legislative session, which can/should refer to an Event.
## Event
- [x] [OpenCivicData Event](http://docs.opencivicdata.org/en/latest/proposals/0004.html)
- [x] [metasausage](http://blog.law.cornell.edu/metasausage/downloads-and-related-information/): download the [Legislative Properties and Classes](http://blog.law.cornell.edu/metasausage/wp-content/plugins/download-monitor/download.php?id=15)
- [x] [LIPARM](http://www.liparm.ac.uk/?page_id=103) has calendar objects
- [x] [iCalendar](http://tools.ietf.org/html/rfc5545)

RDF
- [x] [Schema Event](http://schema.org/Event)
- [x] [LODE Linking Open Descriptions of Events](http://linkedevents.org/ontology/)
- [x] Bio [Event](http://vocab.org/bio/0.1/Event.html)
- [x] [Event Ontology](http://motools.sourceforge.net/event/event.html)
- [x] [Semantic Desktop](http://www.semanticdesktop.org/ontologies/2007/04/02/ncal/), which has review of RDF Calendar
- [x] [RDF Calendar](http://www.w3.org/TR/rdfcal/), replaced by [icaltzd (RDF)](http://www.w3.org/2002/12/cal/icaltzd)
- [x] [Simple Event Model (SEM)](http://www.cs.vu.nl/~guus/papers/Hage11b.pdf) [RDF](http://semanticweb.cs.vu.nl/2009/11/sem/)

**Comment by evdb** [comment]
This was also suggested for PopIt: mysociety/popit#140

The word 'event' has several meanings and is open to misinterpretation.

It is important to make it clear that "Event" as we mean it here is something that happens at a point in time - an occurrence. Not something that occurs over a duration. So an event would be the start of an election campaign (someone declaring themselves as a candidate), or the declaration of results. The whole election campaign from start to finish would not be the event. Hence `events` have a single date, not a start and an end.

It is also not a gathering of people - so a hustings is not an event in this sense. Gathering events (one that people might attend - ie have a `participation` in) are interesting, but beyond the scope of Popolo.

**Comment by tswicegood** [comment]
Talked about popolo and my [tx_people](https://github.com/texas/tx_people) implementation at #mozfest yesterday (Saturday) and covering events came up.  The ability to capture an event in time (gave money to, elected to office, and so on) was one big missing piece for full adoption.

CC'ing @dwillis here, as he's interested in following this thread.

**Comment by jpmckinney** [comment]
Thanks @tswicegood, I've scheduled events for next month, so hopefully I'll have a draft up soon!

**Comment by jpmckinney** [comment]
Not quite November 2013 as promised, but done! http://www.popoloproject.com/specs/event.html
