### ISSUE TITLE
Legislative sessions and terms

### ISSUE THREAD

**Issue by jpmckinney** [popolo-project/popolo-spec#25]
Billy assigns all objects to a legislative term and/or session. How should this be modeled more generally? Do we need terms/sessions in Popolo? Are terms/sessions sufficiently internationalizable? What alternative modeling is there?

Use cases for sessions:
- To mark the date on which all orders (bills, motions, etc.) are expunged
- To disambiguate vote and bill numbers, which are often reset at the start of sessions

Use cases for terms:
- To mark the date on which all (or a subset of) elected officials lose their seats
- To describe the term lengths of posts within the organization
- To determine who has left before the end of the term

If we were to add terms and sessions, we would need to:
- Survey the meaning of these terms in various countries

Properties for Session:
- `name` or `number`
- `start_date`
- `end_date`
- `term_id`

Properties for Term:
- `name` or `number`
- `start_date`
- `end_date`
- `organization_id`

Both can be a subclass of Event.

**Comment by dwillis** [comment]
I think term and session are good properties, along with start and end dates for the sessions. Other possible properties could describe the majority party in each session, which can change.

**Comment by jpmckinney** [comment]
I assume the majority party is a derived property, which can be determined from the membership of the chamber at a given point in time? What are terms and sessions typically used for? What are some use cases?

**Comment by dwillis** [comment]
It _usually_ can be derived, yes, although there are some edge cases; in the US Senate there can be a 50-50 split between two parties, and usually the majority goes to the party of the Vice President (who, constitutionally, serves as the President of the Senate and can cast a vote when votes are a 50-50 tie).

In the US, a "term" is basically a 2-year Congress (we're in the 113th Congress this year, for example). Each congress has two sessions - one for each year. So we're currently in the 1st session of the 113th Congress.

**Comment by jpmckinney** [comment]
The rules around (and the relevance of) the majority party seem to be system-specific - we'd have to do more research to find an international way of representing that information. In the meantime, it can be a property that each implementation adds to session/term objects.

I'm familiar with what terms and sessions _are_ - I'm wondering what they are _used for_. Functionally, they seem to be a way to say "this is the day everyone gets fired" (term) or "this is the day all in-process bills fail" (session). I know that analysts use terms and sessions as a convenient way to summarize information - I don't know if it's merely convenience or if there is a statistically rigorous reason for summarizing information in those units.

To put it a different way: what questions are you asking of your data, whose answers must involve the concepts of sessions and terms?

**Comment by dwillis** [comment]
My mistake - for example, in the Congress sessions are used to track votes, because the roll call number resets to 1 at the start of a new session. So the 113th Congress has two votes that are roll call #1 - one in 2013 and one in 2014. Terms also help to indicate when people don't make it all the way til the designated end - good for querying. Make sense?

**Comment by jpmckinney** [comment]
I've started to list some uses cases in the issue description. In what case would you want to know who doesn't make it to the end, besides curiosity / trivia / inside baseball?

**Comment by dwillis** [comment]
A couple of uses: one is to track those people who have left or are intending to, like [we do for Congress](http://politics.nytimes.com/congress/members/113/house/departures). Related is to track open seats in upcoming elections, and a third would be to help monitor committee assignments, since vacancies usually mean a shift in assignments for the members who remain.

**Comment by jpmckinney** [comment]
Popolo tracks open seats (whether in a chamber or in a committee) as-is - you can query for all Posts that do not have any Memberships with a blank or future `end_date`. Is the current spec insufficient in that respect?

What sort of people visit that departures page? Why do they? I'm trying to evaluate how common a use case it is.

**Comment by dwillis** [comment]
Right - these would be people who perhaps have announced an _intention_ to resign or retire. So the seat (Post) isn't currently open but will be for the next election, in the sense that no incumbent will be running. The spec isn't insufficient, no, but I think there is a value in knowing the future state of the seat. The departures page is admittedly more for political junkies than the average person, but often members who intend to retire may vote differently, knowing that they will not face voters again, and that kind of information can help people evaluate their elected officials. Even those who won't be in that role for long.

**Comment by jpmckinney** [comment]
In terms of intentions/commitments to leave office, one option is to set a future `end_date` on a Membership. There's an open issue #7 about how to represent partial/uncertain/reduced dates, like `2014-01` for "sometime in January, 2014".

The last comment also sounds similar to #20 (which is now merged into #22). Retirement announcements, etc. would be events in a person's timeline, which can reference their membership, and somehow denote that the event implies the eventual end of that membership. This use case doesn't require a concept of session/term.

**Comment by dwillis** [comment]
Both of those sound fine to me, although it would be nice to have term/session for votes when things get around to that.

**Comment by jpmckinney** [comment]
Yup! I've noted that in the main issue description.

**Comment by akuckartz** [comment]
A recent addition to OParl was `oparl:LegislativeTerm` which has only three properties: a name and start and end dates. And `oparl:Body` has a property `legislativeTerm` for those objects. The information is expected to be used for search filters.

**Comment by jpmckinney** [comment]
With the addition of http://www.popoloproject.com/specs/event.html and http://www.popoloproject.com/specs/vote-event.html, the use cases discussed in this issue are fulfilled.

See #22, #29 and #57 for the development of these two classes.
