### ISSUE TITLE
Add Role class?

### ISSUE THREAD

**Issue by jpmckinney** [popolo-project/popolo-spec#31]
Multilingual support may justify a Role class (like in ORG). Maintaining translations on each Post and Membership would be too great a burden; it would be easier to have a Role class with a translatable name field.

**Comment by jpmckinney** [comment]
No one has mentioned this as being an issue. Closing for now.

**Comment by tmtmtmtm** [comment]
Is alternate name + `note` a valid approach for this one?

**Comment by jpmckinney** [comment]
Translations are not alternate names, but the same names in different languages.

**Comment by tmtmtmtm** [comment]
I think I misunderstood the original suggestion here, then. I read it as being an approach when someone didn't want the full overhead of doing it 'properly', and was suggesting that simply adding alternate names, with a note of language code, could be a quick'n'dirty substitute.

**Comment by jpmckinney** [comment]
Except we don't have an "alternate roles" property in Popolo :)

**Comment by tmtmtmtm** [comment]
Ah, yes :)
