### ISSUE TITLE
Add a party-like property to the Membership class

### ISSUE THREAD

**Issue by jpmckinney** [popolo-project/popolo-spec#33]
Once resolved, add more complex examples for the party membership of candidates and members, e.g.
- simple membership
  - between a person and an organization
  - issue: cannot infer whether the person holding a post represents that party in that post
- complex membership
  - issue: the person may be a member of a party, but not represent that party
  - resolution: a party-like property must therefore be on the membership object

Specific example: Ross Anderson, presidential candidate, 2012 ran as many different parties depending on the state:
- AZ: Peace and Freedom
- CT: Justice
- MT: Write-In
- NM: New Mexico Independent Party
- Natural Law Party
- Progressive
- Independent
- Other

**Comment by peterneish** [comment]
Wouldn't a party be an instance of Organisation?

**Comment by jpmckinney** [comment]
In most cases, you wouldn't need to use this `party` property, and would simply use Organizations. However, consider a case where a person is a member of a party and holds a political office. Can you infer that they represent that party while they hold that office? In some jurisdictions, yes; in others, no. The situation becomes impossible if that person belongs to multiple parties and holds multiple offices. In such cases, a `party` property is necessary.

**Comment by peterneish** [comment]
Sounds reasonable, although in some cases it might be a bit too specific. If we want to know the organization that a person is representing in a political office then perhaps Membership needs a  `represents` property that maps to an organization. There could be cases where membership of one organization involves representing a second organization that is not a party, although if we are only talking about legislature then its probably not an issue.

**Comment by jpmckinney** [comment]
Good point, we should consider a different term, like `represents`.

**Comment by jpmckinney** [comment]
Brainstorming possible terms: `representing`, `agentOf`, `onBehalfOf`, `asMemberOf`.

A challenge is that in some legislative systems, for example, members have varying levels of agency with respect to the body they represent. In many jurisdictions, individual members of parties are not spokespeople for that party, so the term should not ascribe too much agency (like `representing` or `agentOf` might).

`asMemberOf` gives the least agency. `onBehalfOf` better matches terms typically used to describe such relationships.

**Comment by jpmckinney** [comment]
@paultag @jamesturk @twneale @evdb @dracos Any feedback on a new term to describe a situation where, for example, a legislator, as member of a committee, is acting on behalf of a party?

See http://lists.w3.org/Archives/Public/public-opengov/2013Sep/0010.html

**Comment by jpmckinney** [comment]
Going with `onBehalfOf`.
