### ISSUE TITLE
Entity name in different languages

### ISSUE THREAD

**Issue by clkao** [popolo-project/popolo-spec#35]
We should be able to define names in different languages for an entity.  For example the organization "Legislative Yuan" should be "立法院" in zh-Hant.

I'd like to propose recommending the use [other_names](http://popoloproject.com/specs/#other-name) with `locale:`-prefix `note` entries for this purpose.  the value after `locale:` is the language of the entry, defined in the [IANA Language Subtag Registry](http://www.iana.org/assignments/language-subtag-registry)

For example:

```
{
  "id": "ly.gov.tw",
  "name": "Legislative Yuan",
  "other_names": [
    {
      "name": "立法院",
      "note": "locale:zh-Hant"
    },
    {
      "name": "Yuan Legislativo",
      "note": "locale:es"
    }
  ]
}
```

**Comment by jpmckinney** [comment]
Thanks @clkao! I have some notes about multilingual support in the appendix here: http://popoloproject.com/appendices/api-patterns.html#internationalization What do you think of the JSON-LD alternatives described there?

**Comment by clkao** [comment]
oh i totally missed the appendix part.

the JSON-LD language map one looks most feasible and least intrusive.  It'd be bad if instead of simple object traversal, you suddenly need to iterate and filter just to get a "default value", as the value object dialect shows.

if we also declare implicit @context for common resource attributes, for example in the organization case, we know that name and other_names/name are likely to have variants and shouldn't require users to define @context.

**Comment by jpmckinney** [comment]
I agree - the language map is probably best. As JSON-LD tools become more popular/available, I expect it will be easier to parse multilingual JSON correctly. I should have JSON-LD contexts done by the end of this month (see #30).

**Comment by jpmckinney** [comment]
@clkao I think we concluded that the options described at http://popoloproject.com/appendices/api-patterns.html#internationalization were sufficient, but if I misunderstood, please request that I re-open the issue.

**Comment by clkao** [comment]
Note that the related appendix url has changed: http://popoloproject.com/appendices/multilingualization.html
