### ISSUE TITLE
Add support for historical organizational hierarchy

### ISSUE THREAD

**Issue by jpmckinney** [popolo-project/popolo-spec#41]
http://lists.w3.org/Archives/Public/public-opengov/2013Sep/0005.html

In order to communicate past relations between organizations in terms of organization hierarchy, add a `parents` property, whose values are instances of a new class, e.g. in JSON:

``` json
{
  "parents": [
    {
      "parent_id": "foo",
      "start_date": "2010-01-01",
      "end_date": "2010-12-31"
    },
    {
      "parent_id": "bar",
      "start_date": "2011-01-01"
    }
  ]
}
```

The new class would have properties `start_date`, `end_date`, `parent_id` and `child_id`, though generally `child_id` will be omitted as it's understood to be the embedding object.

As this new class bears some resemblance to the Membership class, it may be worthwhile to devise an appropriate superclass for both.

**Comment by guglielmo** [comment]
I would add a `current_parent_id` property, just to keep compatibility with code using the standard `parent_id` representation for trees.
- It would be the id of the parent having no `end_date`. 
- It would not exist in case no such parent exists.
- It is assumed that an organization can only have one current_parent, at a given time.

This should cover 99% of the use cases out there, in our context.

**Comment by jpmckinney** [comment]
@guglielmo A related discussion started on the Poplus list about coalitions. I wonder if my proposal in that thread might fit your use case better? https://groups.google.com/forum/#!topic/poplus/yZJfHocAGO0

**Comment by akuckartz** [comment]
See https://github.com/opennorth/popolo-spec/issues/47#issuecomment-34547839 regarding the W3C Organization Ontology.

**Comment by jpmckinney** [comment]
The ORG ontology doesn't model historical _hierarchies_; if Bureau A moves from Department X into Department Y, the ORG ontology has no way of modelling that. You would need to at a minimum be able to track historical values of `org:hasSubOrganization` and `org:subOrganizationOf`.

**Comment by girogiro** [comment]
Ad coalitions: Couldn't we just reuse the `parents` property proposed above for coalitions? Description of _parent organization_ in specification is _The organization that contains this organization_ that more or less fit also for coalitions. For the Poplus discussion example: The "Center party" would have a parent organization "Ruling coalition of Finnish parliament" and another parent "International Democrat Union". Thanks to time period associated to each parent relationship even history of coalitions can be modeled. Without the need to introduce a new `member` property to Membership class.

**Comment by jpmckinney** [comment]
@tmtmtmtm wouldn't consider the coalition to be the parent of the party, and strictly speaking, it is not the parent. In general, I've found that it's best to model things as they are, instead of trying to shoehorn things into a model that is not perfectly true; those inconsistencies sometimes lead to issues down the road.

**Comment by jpmckinney** [comment]
To quote @tmtmtmtm:

> it might just be because I don't see a coalition as being a 'parent' of a party [...] coalitions seem to me to be simple membership based things, rather than a hierarchy (just as a Party isn't the parent of a Person). Is this just a case of "We need some sort of parent relationship anyway for organisations, so maybe we can shoehorn coalitions into that too", or is this actually the best way to handle something like this?

**Comment by girogiro** [comment]
I am wondering that introducing multiple parents in `parents` property there are going to be two similar time-framed many-to-many relationship mechanisms between organizations - one using `parents` property and another through _Membership_ class. Couldn't be an organizational hierarchy modeled using _Membership_ class with "parent" or "child" value in its `label` property? It allows to model historical organizational hierarchy as well as multiple organization hierarchies without any extension of current specification.

**Comment by jpmckinney** [comment]
In either case, we need an additional property on the `Membership` class (in JSON) for the member organization (we can't use `person_id` for that!). The `organization_id` is always the parent, and the `member_id` will always be the member, so there's no need to put a code in the `label` property - unless I misunderstood.

There are two suggested mechanisms, but they are not the same. A subdivision of a company is not a "member" of that company, it is a "suborganization" of the company, and should use `org:subOrganizationOf` (which in JSON is `parent_id`). If a company joins (or leaves) an industry group, it is a "member" of that group. It is not a suborganization of that group.

**Comment by jpmckinney** [comment]
I'm closing this issue in favor of #47, whose goal is to find a general way of modeling all historical values of properties, and #55, which is about modeling organizational memberships like coalitions.

**Comment by kaerumy** [comment]
Sorry a little bit late to this, but we're encountering the need for this in Malaysia.

Use case:

Agencies or government owned companies are reorgnised from one Ministry to another, or other government instruments.

This changes the relationships of oversight boards, committees, responsible ministers between periods, but the memberships/posts of the organization moved around are often still the same before and after the reorganization.
