### ISSUE TITLE
Add dates to ContactDetail

### ISSUE THREAD

**Issue by jpmckinney** [popolo-project/popolo-spec#46]
e.g.

> older contact details may help to discover that one of the MP's offices three years ago was located at the same address as a company of a man he claims not to know

Use `valid_from` and `valid_through`?

**Comment by jpmckinney** [comment]
http://popoloproject.com/specs/contact-detail.html

**Comment by tmtmtmtm** [comment]
I hadn't seen this issue before, or I would have noted that 'through' meaning end, rather than middle, is mainly an American English usage, and sounds quite odd in British English...

**Comment by jpmckinney** [comment]
Schema.org also has validUntil, which to me sounds like it should have the same meaning. I'll change to that. validThrough was from GoodRelations, which Schema.org adopted.

**Comment by girogiro** [comment]
JSON schema of ContactDetail and example of its JSON serialization still use `valid_through`. Is it a bug or intention?

**Comment by jpmckinney** [comment]
That is a bug! Thanks for reporting. I've corrected those files.
