### ISSUE TITLE
Add other_labels to Posts

### ISSUE THREAD

**Issue by tmtmtmtm** [popolo-project/popolo-spec#51]
People and Organizations have alternative/historic names; Posts currently don't.

You might want to say, for example, that the post of Prime Minister used to be called 'First Minister', or that 'CEO' is an alternative name for 'Chief Executive Officer'.

**Comment by jpmckinney** [comment]
Can you write a pull request? I would keep the semantics to strictly alternate names. Former values will be addressed by #47

**Comment by jpmckinney** [comment]
Any opinion on whether the name should be `other_labels` or `alternate_labels`?

**Comment by tmtmtmtm** [comment]
I'm travelling at the minute, so can't do much this week. On the name, I've no strong opinions, other than preferring consistency with everything else.

**Comment by jpmckinney** [comment]
cf. #53 `other_names` may not have been the best choice of property name.

**Comment by jpmckinney** [comment]
Do alternate labels need a `note` property? If not, then the RDF and JSON can be better aligned.

**Comment by tmtmtmtm** [comment]
Sorry, this one completely fell off my radar. 

I could see _possible_ cases where a Post could have different names that you might need to explain (e.g. in somewhere like BiH or Northern Ireland, where the structures codify having different identity designations, and where terminology is itself highly politicised, it's certainly feasible that certain posts could be named differently by each of those), but I can't think of an _actual_ example right now.

**Comment by tmtmtmtm** [comment]
Hmm, actually, one possible example is in the terminology around "Deputy First Minister", "deputy First Minister", "Joint First Minister", "Co-First Minister" etc in Northern Ireland. http://en.wikipedia.org/wiki/First_Minister_and_deputy_First_Minister#Terminology

This doesn't necessarily _need_ a `note`, but I could see why someone might want to add one.

**Comment by jpmckinney** [comment]
I think I'll encode it as a simple array of strings. The Northern Ireland example doesn't suggest obvious cases where an alternate label would be preferred over the primary label (which is the primary use case for `note` in `other_names`).

**Comment by jpmckinney** [comment]
Added: http://popoloproject.com/specs/post.html#skos:altLabel
