### ISSUE TITLE
Documentation of Membership, after member property insertion

### ISSUE THREAD

**Issue by guglielmo** [popolo-project/popolo-spec#66]
After the `member` property has been added to the `Membership` class, in #55, the documentation correctly refers to the member property, as a pointer to a `person` or an `organization`.

The presence of `person` and `person_id`, in the json example, schema and the json-ld context, may be a bit misleading for newcomers.

It should be clarified, maybe in a footnote, that they're still there for the sake of back-compatibility. An example similar to the json example 2.6, but with mixed person/organization memberships, could be used in the JSON and RDF sections of the Membership specs.

**Comment by jpmckinney** [comment]
In the [serialization section](http://popoloproject.com/specs/membership.html#serialization), there is already the note:

> - The term `person` or `person_id` is used in the common case or relating a person to an organization. The term `member` may be used to relate either a person or an organization to an organization ([see an example](/appendices/examples.html#party-coalition)).

`person_id` is not treated as a deprecated property - it is just as good as `member`. We maintain it because relating people to orgs is an extremely common use case - much more common than relating orgs to orgs.

Should the above note be made clearer? Should `person_id` be mentioned elsewhere in the documentation?

**Comment by guglielmo** [comment]
No, I overlooked that, it's clear enough and the json example is also
linked.

On 28 July 2014 22:20, James McKinney notifications@github.com wrote:

> In the serialization section, there is already the note:
> - The term person or person_id is used in the common case or relating
>   a person to an organization. The term member may be used to relate
>   either a person or an organization to an organization (see an example
>   http://appendices/examples.html#party-coalition).
>   
>   person_id is not treated as a deprecated property - it is just as good
>   as member. We maintain it because relating people to orgs is an extremely
>   common use case - much more common than relating orgs to orgs.
> 
> Should the above note be made clearer? Should person_id be mentioned
> elsewhere in the documentation?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/opennorth/popolo-spec/issues/66#issuecomment-50393609
> .

## 

Guglielmo Celata

microcredito online - http://www.kiva.org/lender/guglielmocelata
per una politica trasparente - http://www.openpolis.it

**Comment by jpmckinney** [comment]
Okay, I guess that closes the issue.
