### ISSUE TITLE
Organization memberships ambiguity

### ISSUE THREAD

**Issue by guglielmo** [popolo-project/popolo-spec#67]
The `Membership.member` property, added in #55, seems to leave space for ambiguity as to the sense of the `memberships` attribute in the serialization of the `Organization` class.

Does `Organization.memberships` refer to the relationships in which the Organization is the _container_ of other persons/organizations, or the those in which the Organization is _member_ of some other Organization?

**Comment by jpmckinney** [comment]
I think it has to be both - otherwise, we would need to find distinct terms for the "is a member of" and the "has members" cases. What do you think? I added the following paragraph for now:

> In the case of an organization's memberships, an organization may both have members and be a member of other organizations. As such, the `organization_id` property _should_ be present on each subdocument, to avoid ambiguity.

**Comment by jpmckinney** [comment]
I've also updated the description of the `memberships` term in Organization's JSON Schema to be "The memberships of the members of the organization and of the organization itself". Closing unless there is still an issue as to ambiguity - or unless the resolution makes implementation more difficult.
