### ISSUE TITLE
Popolo lint

### ISSUE THREAD

**Issue by jpmckinney** [popolo-project/popolo-spec#68]
Create a web service like http://csvlint.io/ (OKFest request)

**Comment by akuckartz** [comment]
I am also interested in that topic for JSON-LD based OpenGovLD: https://github.com/OpenGovLD/specs/issues/67

**Comment by jpmckinney** [comment]
Also relevant to #107

**Comment by jmatsushita** [comment]
Would you need linting for JSON (which would be "just" JSON Schema validation), as well as linting for other file formats representing the data? Could you validate a SQL Schema? a CSV with JSON Table Schema or without - a la HXL? JSON-LD?

**Comment by jpmckinney** [comment]
For a CSV with an HXL-style row, the linter would validate that row. The CSV can then be transformed to JSON to take advantage of whatever eventual JSON Schema validation tools exist.

For metadata files about CSVs, I don't think there's any Popolo-specific validation to perform. The metadata file is either valid W3C tabular metadata, JSON Table Schema, etc. or it isn't.

JSON-LD would be validated in a similar way as plain JSON. There are some small documented differences in how Popolo serializes to JSON-LD versus JSON, so there'd be a different linter for it. 

I don't think there's much interest in validating a SQL schema. It would be difficult/impossible anyway, since people may have all sorts of reasons for designing their schema a particular way, e.g. using PostgreSQL hstore or JSON columns versus creating new tables, etc. What matters is how the project publishes the data stored in whatever database. Popolo isn't about regulating databases. We're trying to achieve interoperability at the data interchange layer, not the data storage layer. It's not expected that two Popolo implementations can read directly from the same database.

**Comment by jmatsushita** [comment]
> For metadata files about CSVs, I don't think there's any Popolo-specific validation to perform. The metadata file is either valid W3C tabular metadata, JSON Table Schema, etc. or it isn't.

You think it's outside of the scope of the spec to recommend publishing popolo compatible data files with metadata that clearly maps or identifies columns to specific popolo classes and properties to allow discovery? Or maybe the key use case is that CSV files are published with a header row that is already using Popolo classes and property names? Maybe its a more pragmatic choice and the main case, but I'm wondering about the possibility for CSV file maintainers to add popolo support by editing (or adding) a metadata file that explains the mappings.

> JSON-LD would be validated in a similar way as plain JSON. There are some small documented differences in how Popolo serializes to JSON-LD versus JSON, so there'd be a different linter for it.

Don't you need to validate JSON-LD (not just for syntax but for conformance to the spec) against a vocabulary? Like the Schema.org vocabulary for https://developers.google.com/structured-data/testing-tool/ for instance?

Any stupidity is entirely the responsibility of my tiredness...

**Comment by jpmckinney** [comment]
The spec can suggest/recommend using W3C tabular metadata files or JSON Table Schema files to provide a machine-readable mapping with whatever headers are in a CSV file to Popolo's terms. What technology people use to map things to Popolo is really up to them, but Popolo's documentation can provide some pointers. Anyway, my comment was about the **validation** of these sorts of files, not about whether to use these sorts of files at all.

Sure, there can be whatever LD validations people want. Popolo has extremely little to validate though. It has almost no required fields, very few restrictions on format... The main restrictions are on range.
