### ISSUE TITLE
Missing embedding properties

### ISSUE THREAD

**Issue by jpmckinney** [popolo-project/popolo-spec#76]
The original set of classes lack properties for embedding the newer classes, e.g. Organization lacks a `motions` property.

**Comment by akuckartz** [comment]
For JSON-LD this probably will make it necessary to create a subclass of `org:Organization`. Maybe `opengov:Organization` ;-)

**Comment by jpmckinney** [comment]
It's possible to add properties to classes belonging to other namespaces.

**Comment by girogiro** [comment]
Organization has property `parent`. Perhaps it should have also a reverse `children` property.

**Comment by jpmckinney** [comment]
Thanks, @girogiro ! Forgot that. I'll try to do this today.

**Comment by akuckartz** [comment]
It is possible, yes, but not recommended. I will attempt to provide reasons later.

[EDIT: I withdraw that statement. One can legitimately add properties to classes belonging to other namespaces (as long as one controls the namespace of the property).]

**Comment by jpmckinney** [comment]
@akuckartz Please open a new issue when ready.

I've added to JSON Schema:
- Area#memberships, #organizations, #posts, #children
- Organization#motions, #vote_events, #votes, #children (`org:hasSubOrganization`)
- Person#motions, #speeches, #votes

For JSON-LD contexts, I'll have to think of appropriate inverse property names, i.e. inverses of `opengov:area`, `gn:parentFeature`, `schema:publisher`, `schema:organizer`, `schema:agent`, and `schema:creator`.

**Update:** Instead found JSON-LD reverse properties. Had searched for "inverse" earlier.

**Comment by jpmckinney** [comment]
JSON-LD contexts are done too!
