### ISSUE TITLE
Add One Line Description and Description property for Organization

### ISSUE THREAD

**Issue by kaerumy** [popolo-project/popolo-spec#78]
There are a lot of obscure government departments, government owned entities as well as private sector entities. These fields are needed by users using popolo standards to map out people & organizations for transparency reasons.

**Comment by akuckartz** [comment]
Can `org:purpose` (http://www.w3.org/TR/vocab-org/#org:purpose) and/or `org:classification` (http://www.w3.org/TR/vocab-org/#org:classification) be used for this?

**Comment by jpmckinney** [comment]
`org:classification` has a range of `skos:ConceptScheme` and is already in use to classify the org. `org:purpose` has a more specific meaning than what @kaerumy describes.

I think we can just add `dcterms:description` and `dcterms:abstract` for these use cases. @kaerumy Can you give me an example of a short description of an org. for this use case?

**Comment by kaerumy** [comment]
# Description Examples

## Government department

The Subang Jaya Municipal Council (MPSJ) is a local council established in accordance with the Local Government Act 1976 (Act 171) under Section 4. 

## Statutory bodies:

Federal Land Consolidation and Rehabilitation Authority (FELCRA) is a fully Government owned company whose objective is to develop rural sector by helping its community to participate in national economic activities, thus improving their standard of living.

The Port Klang Authority (PKA) is a statutory corporation administrating Port Klang.

The Selangor State Development Corporation or Perbadanan Kemajuan Negeri Selangor is a state development corporation in Selangor, 

## Private Companies

Bina Puri Holdings Bhd is a public listed company on the Main Board of Bursa Malaysia Berhad with diverse business activities include investment holdings, civil and building engineering management, property development, highway concessionaire, quarry operations, manufacturing of construction materials, polyurethane system house, utilities and hospitality management.

# Abstract Example

The Subang Jaya Municipal Council (MPSJ) was established in accordance with the Local Government Act 1976 (Act 171) under Section 4. Previously it was called the Petaling District Council before being known now as the Subang Jaya Municipal Council. In 1994, the Selangor State Government decided to upgrade the Petaling District Council to Subang Jaya Municipal Council.

The purpose of this upgrade was to reorganise the administrative organisation in facing the pressures of physical, social, economic and environmental conservation developments. The Selangor State Government Gazette No. 62, Subang Jaya Municipal Council was gazetted on 2 January 1997 according to 1192 gazetted plan with a site area of 16,180 hectares and is divided into seven (7) Planning Blocks in accordance with the Subang Jaya Municipal Council Local Plan 2020 (RTMPSJ 2020), namely:
- Planning Block 1 (Subang Jaya - USJ);
- Planning Block 2 (Subang Hi - Tech);
- Planning Block 3 (Putra Heights);
- Planning Block 4 (Kinrara);
- Planning Block 5 (Puchong);
- Planning Block 6 (Bandar Putra Permai) and
- Planning Block 7 (Seri Kembangan)
  Geographical Location of the Subang Jaya Municipal Council

The Subang Jaya Municipal Council (MPSJ) is one of the Local Authorities located within the Klang Valley Region. The area covers 161.8 square kilometres. It consists of two (2) sub-districts namely Damansara and Petaling.

MPSJ has a strategic location because it borders the Kuala Lumpur City Hall (DBKL), Shah Alam City Council (MBSA), Petaling Jaya City Council (MBPJ) and the Klang Municipal Council (MPK).
Current Land Use Information of the Subang Jaya Municipal Council Area
Current land use according to the Subang Jaya Municipal Council Local Plan 2020 (RTMPSJ 2020) which was gazetted on 27 May 2010 with the gazette number 1566, specifies that the largest land use is the residential land use, covering an area of 2,996.99 hectares which is 18.52% of the overall area of MPSJ. This is followed by industrial land use areas of 989.13 hectares (6.11%), commerce and services covering 495.05 hectares (3.06%) as well as institutional and community facilities covering 1,847.85 hectares (11.42%).

**Comment by jpmckinney** [comment]
Thanks @kaerumy ! I'll add these shortly. `abstract` will be for the short version, btw.

**Comment by akuckartz** [comment]
While we are discussing this: When a committee is created there usually exists a document (motion?) with the decision and charter of the committee. Is there any property which can be used to link to such resources?

**Comment by jpmckinney** [comment]
Not yet. I expect there may be several use cases around linking objects (e.g. organizations) to documents (e.g. charter, etc.). We can either have single-function properties, like a `charter` property, or we can do something similar to [Open Contracting](http://ocds.open-contracting.org/standard/r/1__0__RC/en/schema/reference/#document), where there is `documents` array, where the document's type ("charter") can be selected from a code list. We can open a new issue for that.

**Comment by kaerumy** [comment]
@jpmckinney thanks, now I know, usually in CMS's dc:description often implemented as abstract.

http://dublincore.org/documents/2012/06/14/dcmi-terms/#terms-abstract
http://dublincore.org/documents/2012/06/14/dcmi-terms/#terms-description
