### ISSUE TITLE
How to encourage JSON-LD usage ?

### ISSUE THREAD

**Issue by akuckartz** [popolo-project/popolo-spec#81]
I am working on this question for the W3C Open Government Community Group:
How can the usage of JSON-LD be encouraged ?

Better written reasons, use cases, tutorials etc. ? Tools ? Platform ?

**Comment by jpmckinney** [comment]
For anyone who publishes Popolo JSON, whether they include a `@context` property or not, the Popolo JSON-LD contexts are implicit and can apply to their JSON, which is how Popolo encourages JSON-LD without implementers even knowing that they're using it.

For encouraging JSON-LD in general, this is probably not the best issue queue.

**Comment by akuckartz** [comment]
Thanks for the quick reply. I do not think that this implicit approach works - which is unfortunate - but that can better be discussed on the W3C OG CG mailing list.
