### ISSUE TITLE
Modelling the House of Lords

### ISSUE THREAD

**Issue by dracos** [popolo-project/popolo-spec#95]
I am modelling the members of the House of Lords, and I'm not entirely sure where to put the bits of their names (if I want to do that :) ). As one example, Lord Green of Deddington – I have:
- name: Lord Green of Deddington
- given_name: Andrew Fleming
- family_name: Green
- honorific_prefix: Lord
- honorific_suffix: KCMG

But there's not really anywhere suitable for the "Deddington" to go. I'm currently considering putting Deddington in an `other_name` field with some custom attributes (e.g. also `county` to give the full location of the territorial part), or alternatively adding a custom `lordof_name` or similar.

When a Lord chooses a different name from their previous family name (e.g. John Gummer => Lord Deben), I'm probably going to put Deben in the `family_name`, that seems okay. Thoughts welcome :)

**Comment by jpmckinney** [comment]
On one hand, do you _need_ to have a property for each name component?

In a mobile version, for example, you might display only a person's `honorific_prefix` and `family_name` to save space. In this mobile example, you wouldn't even need to store anything in `given_name` – since it's never used; you would just have `name` for the desktop version and `honorific_prefix` and `family_name` for the mobile version.

So, the question is, in what case is a "lord of" name component needed in isolation from the other name components?

On the other hand, maybe you just want to split names into components anyway. In that case, I'd look into how people have typically analyzed such names. I would be surprised to learn that analyses and histories of such names in the UK had never come up with a set of terms/taxonomy/vocabulary for these name components.

That said, I'm much enthused by `domain_name` :)

**Comment by dracos** [comment]
'Lord Harris' and 'Lord Harris of Peckham' are two different people, so you'd be quite confusing if you did anything like your mobile view with them :) The only use we put the separate part is to enable some sort of "place" lookup to see if someone is lord of a particular location (and then you wouldn't want to search their surnames), so it does have an existing use, and our existing data has it separate. Yeah, I can just copy what data.parliament.uk uses (which is, it appears, Rank:Lord, Title:Green of Deddington, Prenominal:The, Suffix:KCMG, Surname:Green, Forename:Andrew, MiddleNames:Fleming, IsByVirtue:True, etc), I just wondered if they fitted better with the existing spec at all.

**Comment by jpmckinney** [comment]
I think adding a new name component like data.parliament.uk's `Title` is best - though it repeats the Surname in their case. I'd prefer a different term than `title` though, since FOAF uses `title` and LDAP uses `personalTitle` to refer to prefixes like "Mr.". What are your thoughts on naming? Any other terms you've encountered?

I've seen the word `estate` used sometimes to refer to things like "Deddington".

**Comment by dracos** [comment]
It might not be a repeat of the surname if the person's surname differs, as mentioned :)

I believe it's a territorial designation. Continuing my example, Lord Green of Deddington's full introduction was: "Sir Andrew Fleming Green KCMG, having been created Baron Green of Deddington, of Deddington in the County of Oxfordshire" – the designation after the very important comma may be the same place as that used in the main title (if there is one), or different; there may be more than one, and so on.

TheyWorkForYou's XML uses `lordname`, `lordofname`, `lordofname_full` (in cases where the territorial designation doesn't match, or there is no `lordofname`), and `county` (though it's not always a county, and if there's two territories, the second one is just included in a long string in `county`, I doubt anyone is using those!).

**Comment by jpmckinney** [comment]
Can you give a example of lordname, lordofname, lordofname_full and county, so I can see what goes where?

**Comment by dracos** [comment]
https://github.com/mysociety/parlparse/blob/master/members/peers-ucl.xml is all the XML data on peers. Lord Lisvane is an example of the two places; Lord Deben as above; Lord Kennedy of Southwark has a different designation pre and post comma.

**Comment by jpmckinney** [comment]
`lordofname_full` seems to be to produce an addition of `, of <lordofname_full>` So the pattern seems to be:

`title` `lordname`[ of `lordofname`][, of `lordofname_full`][ in `county`]

Some have a `lordofname_full` without a `lordofname`, some have both. I'm not sure of the meaning of the comma.

**Comment by jpmckinney** [comment]
I might suggest having one OtherName for the Lord name and another for the non-Lord name. This would solve Lord Deben. There'd be 3 new terms for `lordofname`, `lordofname_full` and `county`.

**Comment by dracos** [comment]
The data is probably not complete in that XML; all modern life peerage titles will have a territorial designation, I think. It is not part of the actual peerage title (that's what the comma is ending), but is given in the patent of creation. `lordname` is optional as well if there is a `lordofname`, e.g. the Duke of Norfolk, or the Earl of Erroll (or, in TheyWorkForYou's way of looking at them, the Archbishop of Canterbury).

If you have the details at the top level, should you repeat them in an OtherName, to e.g. show all the properties that are included within it?

**Comment by jpmckinney** [comment]
If you like, you can even use no top-level name properties, and only `other_names`. You'd do this if you wanted to avoid promoting any name to "primary", or if you wanted all names to be consistently located in the data structure.

I may have misunderstood the question though.

**Comment by jpmckinney** [comment]
@dracos I think the conclusion of this thread is to add some UK-specific terms to store the name components that don't occur elsewhere in the world. Were there any open issues to solve in Popolo?

**Comment by akuckartz** [comment]
Some people are thinking about an extension for schema.org for such details of names.

**Comment by jpmckinney** [comment]
Do you have a link?

**Comment by akuckartz** [comment]
@jpmckinney

> Do you have a link?

No, unfortunately there is no coordinated effort yet to create a schema.org extension for person names. But I think it would make sense to do that or create a vocabulary. Properties/components of person  names come up again and again. And @danbri also has mentioned somewhere that such an extension perhaps would make sense.

**Comment by danbri** [comment]
http://www.kalzumeus.com/2010/06/17/falsehoods-programmers-believe-about-names/ is worth a read.

Also http://www.w3.org/International/questions/qa-personal-names

**Comment by danbri** [comment]
One idea I've been toying with is to have an (optional and additional) representation of someone's name as actual HTML markup, so that <span> sections could be tagged in various ways, while preserving the general overall order (which gets lost if broken out into parts).

**Comment by jpmckinney** [comment]
There's an OASIS standard that implements that idea (xNL) (XML, not HTML, but same idea): http://docs.oasis-open.org/ciq/v3.0/specs/ciq-specs-v3.html

See the extreme example at http://docs.oasis-open.org/ciq/v3.0/prd03/specs/ciq-specs-v3-prd3.html#_Ref174170633

**Comment by jpmckinney** [comment]
> @dracos I think the conclusion of this thread is to add some UK-specific terms to store the name components that don't occur elsewhere in the world. Were there any open issues to solve in Popolo?

I think we've resolved the questions that this issue was originally created to answer. If people have unresolved issues, please create new ones.
