### ISSUE TITLE
Start/end times as well as dates

### ISSUE THREAD

**Issue by dracos** [popolo-project/popolo-spec#96]
I realise that in almost all cases start/end dates are quite enough. I have two cases in TheyWorkForYou where a membership knowingly changes during a day:
- http://www.theyworkforyou.com/ni/?id=2015-01-12.4.1 – Mitchel McLaughlin is Sinn Féin at the start (12.30pm), but is elected Speaker at 1.15pm at http://www.theyworkforyou.com/ni/?id=2015-01-12.4.1#g4.39
- Similarly, William Hay is DUP at http://www.theyworkforyou.com/ni/?id=2007-05-08.5.0#g5.14 (some point between 10.30 and 11.q5) but is Speaker at http://www.theyworkforyou.com/ni/?id=2007-05-08.6.0 (11.15am).

(A Speaker is party neutral and drops their party alignment, this is not simply being given a new office membership.) I have just hard-coded these two, it's not worth doing anything more, but I wondered if it was worth having optional start/end time attributes on memberships also.

**Comment by jpmckinney** [comment]
We can extend the `start_date` and `end_date` regular expressions to include times. What do you think?

**Comment by breyten** [comment]
Sounds fine with me. In the Netherlands we also have the scenarios like @dracos described above.

**Comment by jpmckinney** [comment]
@dracos How does adding time to the date properties sound? It just means splitting on the letter "T" in the ISO 8601 format (or actually parsing the date, which you're probably doing anyway).

**Comment by dracos** [comment]
Sounds good to me (bar confusion over it being called a date, I guess).

**Comment by akuckartz** [comment]
:+1:
